# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/courses/compiler_principles/compiler/Clike_Compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/courses/compiler_principles/compiler/Clike_Compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/courses/compiler_principles/compiler/Clike_Compiler/CMakeFiles /mnt/d/courses/compiler_principles/compiler/Clike_Compiler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/courses/compiler_principles/compiler/Clike_Compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named omp_gen

# Build rule for target.
omp_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omp_gen
.PHONY : omp_gen

# fast build rule for target.
omp_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omp_gen.dir/build.make CMakeFiles/omp_gen.dir/build
.PHONY : omp_gen/fast

#=============================================================================
# Target rules for targets named acc_gen

# Build rule for target.
acc_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acc_gen
.PHONY : acc_gen

# fast build rule for target.
acc_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acc_gen.dir/build.make CMakeFiles/acc_gen.dir/build
.PHONY : acc_gen/fast

#=============================================================================
# Target rules for targets named clike

# Build rule for target.
clike: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clike
.PHONY : clike

# fast build rule for target.
clike/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/build
.PHONY : clike/fast

src/CodeGen.o: src/CodeGen.cpp.o
.PHONY : src/CodeGen.o

# target to build an object file
src/CodeGen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/CodeGen.cpp.o
.PHONY : src/CodeGen.cpp.o

src/CodeGen.i: src/CodeGen.cpp.i
.PHONY : src/CodeGen.i

# target to preprocess a source file
src/CodeGen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/CodeGen.cpp.i
.PHONY : src/CodeGen.cpp.i

src/CodeGen.s: src/CodeGen.cpp.s
.PHONY : src/CodeGen.s

# target to generate assembly for a file
src/CodeGen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/CodeGen.cpp.s
.PHONY : src/CodeGen.cpp.s

src/SymbolTable.o: src/SymbolTable.cpp.o
.PHONY : src/SymbolTable.o

# target to build an object file
src/SymbolTable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/SymbolTable.cpp.o
.PHONY : src/SymbolTable.cpp.o

src/SymbolTable.i: src/SymbolTable.cpp.i
.PHONY : src/SymbolTable.i

# target to preprocess a source file
src/SymbolTable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/SymbolTable.cpp.i
.PHONY : src/SymbolTable.cpp.i

src/SymbolTable.s: src/SymbolTable.cpp.s
.PHONY : src/SymbolTable.s

# target to generate assembly for a file
src/SymbolTable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/SymbolTable.cpp.s
.PHONY : src/SymbolTable.cpp.s

src/ast.o: src/ast.cpp.o
.PHONY : src/ast.o

# target to build an object file
src/ast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/ast.cpp.o
.PHONY : src/ast.cpp.o

src/ast.i: src/ast.cpp.i
.PHONY : src/ast.i

# target to preprocess a source file
src/ast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/ast.cpp.i
.PHONY : src/ast.cpp.i

src/ast.s: src/ast.cpp.s
.PHONY : src/ast.s

# target to generate assembly for a file
src/ast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/ast.cpp.s
.PHONY : src/ast.cpp.s

src/astprinter.o: src/astprinter.cpp.o
.PHONY : src/astprinter.o

# target to build an object file
src/astprinter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/astprinter.cpp.o
.PHONY : src/astprinter.cpp.o

src/astprinter.i: src/astprinter.cpp.i
.PHONY : src/astprinter.i

# target to preprocess a source file
src/astprinter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/astprinter.cpp.i
.PHONY : src/astprinter.cpp.i

src/astprinter.s: src/astprinter.cpp.s
.PHONY : src/astprinter.s

# target to generate assembly for a file
src/astprinter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/astprinter.cpp.s
.PHONY : src/astprinter.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parser.o: src/parser.cpp.o
.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

src/tokenize.o: src/tokenize.cpp.o
.PHONY : src/tokenize.o

# target to build an object file
src/tokenize.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/tokenize.cpp.o
.PHONY : src/tokenize.cpp.o

src/tokenize.i: src/tokenize.cpp.i
.PHONY : src/tokenize.i

# target to preprocess a source file
src/tokenize.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/tokenize.cpp.i
.PHONY : src/tokenize.cpp.i

src/tokenize.s: src/tokenize.cpp.s
.PHONY : src/tokenize.s

# target to generate assembly for a file
src/tokenize.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clike.dir/build.make CMakeFiles/clike.dir/src/tokenize.cpp.s
.PHONY : src/tokenize.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... acc_gen"
	@echo "... intrinsics_gen"
	@echo "... omp_gen"
	@echo "... clike"
	@echo "... src/CodeGen.o"
	@echo "... src/CodeGen.i"
	@echo "... src/CodeGen.s"
	@echo "... src/SymbolTable.o"
	@echo "... src/SymbolTable.i"
	@echo "... src/SymbolTable.s"
	@echo "... src/ast.o"
	@echo "... src/ast.i"
	@echo "... src/ast.s"
	@echo "... src/astprinter.o"
	@echo "... src/astprinter.i"
	@echo "... src/astprinter.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/tokenize.o"
	@echo "... src/tokenize.i"
	@echo "... src/tokenize.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

